/**
 * ColdStorage — Shared Types (Auto-Generated)
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: node shared/generate-types.mjs
 *
 * Source: backend/prisma/schema.prisma
 * Generated: 2026-07-02T19:40:23.972Z
 */

// ════════════════════════════════════════════════
// Enums
// ════════════════════════════════════════════════

export type UserRole = 'SUPER_ADMIN' | 'ADMIN' | 'OWNER' | 'STAFF' | 'FARMER' | 'BUYER';
export const UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN' as const,
  ADMIN: 'ADMIN' as const,
  OWNER: 'OWNER' as const,
  STAFF: 'STAFF' as const,
  FARMER: 'FARMER' as const,
  BUYER: 'BUYER' as const,
} as const;

export type UserStatus = 'PENDING_VERIFICATION' | 'ACTIVE' | 'SUSPENDED' | 'DEACTIVATED';
export const UserStatus = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION' as const,
  ACTIVE: 'ACTIVE' as const,
  SUSPENDED: 'SUSPENDED' as const,
  DEACTIVATED: 'DEACTIVATED' as const,
} as const;

export type FacilityStatus = 'PENDING_REVIEW' | 'ACTIVE' | 'SUSPENDED' | 'DECOMMISSIONED';
export const FacilityStatus = {
  PENDING_REVIEW: 'PENDING_REVIEW' as const,
  ACTIVE: 'ACTIVE' as const,
  SUSPENDED: 'SUSPENDED' as const,
  DECOMMISSIONED: 'DECOMMISSIONED' as const,
} as const;

export type StorageType = 'BAG' | 'BULK' | 'HYBRID';
export const StorageType = {
  BAG: 'BAG' as const,
  BULK: 'BULK' as const,
  HYBRID: 'HYBRID' as const,
} as const;

export type ChamberStatus = 'OPERATIONAL' | 'MAINTENANCE' | 'OFFLINE';
export const ChamberStatus = {
  OPERATIONAL: 'OPERATIONAL' as const,
  MAINTENANCE: 'MAINTENANCE' as const,
  OFFLINE: 'OFFLINE' as const,
} as const;

export type CommodityCategory = 'POTATO' | 'ONION' | 'VEGETABLES' | 'FRUITS' | 'DAIRY' | 'FROZEN_SEAFOOD' | 'FROZEN_MEAT' | 'PROCESSED_FOOD' | 'SEEDS' | 'OTHER';
export const CommodityCategory = {
  POTATO: 'POTATO' as const,
  ONION: 'ONION' as const,
  VEGETABLES: 'VEGETABLES' as const,
  FRUITS: 'FRUITS' as const,
  DAIRY: 'DAIRY' as const,
  FROZEN_SEAFOOD: 'FROZEN_SEAFOOD' as const,
  FROZEN_MEAT: 'FROZEN_MEAT' as const,
  PROCESSED_FOOD: 'PROCESSED_FOOD' as const,
  SEEDS: 'SEEDS' as const,
  OTHER: 'OTHER' as const,
} as const;

export type PaymentMethod = 'CASH' | 'UPI' | 'BANK_TRANSFER' | 'CHEQUE';
export const PaymentMethod = {
  CASH: 'CASH' as const,
  UPI: 'UPI' as const,
  BANK_TRANSFER: 'BANK_TRANSFER' as const,
  CHEQUE: 'CHEQUE' as const,
} as const;

export type DocumentType = 'FSSAI_REGISTRATION' | 'STATE_HORTICULTURE_LICENSE' | 'POLLUTION_CONSENT' | 'FIRE_SAFETY_CERTIFICATE' | 'WDRA_REGISTRATION' | 'GST_CERTIFICATE' | 'BUSINESS_REGISTRATION' | 'OTHER';
export const DocumentType = {
  FSSAI_REGISTRATION: 'FSSAI_REGISTRATION' as const,
  STATE_HORTICULTURE_LICENSE: 'STATE_HORTICULTURE_LICENSE' as const,
  POLLUTION_CONSENT: 'POLLUTION_CONSENT' as const,
  FIRE_SAFETY_CERTIFICATE: 'FIRE_SAFETY_CERTIFICATE' as const,
  WDRA_REGISTRATION: 'WDRA_REGISTRATION' as const,
  GST_CERTIFICATE: 'GST_CERTIFICATE' as const,
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION' as const,
  OTHER: 'OTHER' as const,
} as const;

export type DocumentStatus = 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'EXPIRED';
export const DocumentStatus = {
  PENDING_REVIEW: 'PENDING_REVIEW' as const,
  APPROVED: 'APPROVED' as const,
  REJECTED: 'REJECTED' as const,
  EXPIRED: 'EXPIRED' as const,
} as const;

export type PricingModel = 'PER_DAY_PER_MT' | 'PER_MONTH_PER_MT' | 'PER_SEASON' | 'FLAT_RATE';
export const PricingModel = {
  PER_DAY_PER_MT: 'PER_DAY_PER_MT' as const,
  PER_MONTH_PER_MT: 'PER_MONTH_PER_MT' as const,
  PER_SEASON: 'PER_SEASON' as const,
  FLAT_RATE: 'FLAT_RATE' as const,
} as const;

export type PricingStatus = 'ACTIVE' | 'PENDING_APPROVAL' | 'REJECTED' | 'ARCHIVED';
export const PricingStatus = {
  ACTIVE: 'ACTIVE' as const,
  PENDING_APPROVAL: 'PENDING_APPROVAL' as const,
  REJECTED: 'REJECTED' as const,
  ARCHIVED: 'ARCHIVED' as const,
} as const;

export type LotStatus = 'INTAKE_PENDING' | 'STORED' | 'PARTIALLY_RELEASED' | 'FULLY_RELEASED' | 'EXPIRED' | 'DISPOSED';
export const LotStatus = {
  INTAKE_PENDING: 'INTAKE_PENDING' as const,
  STORED: 'STORED' as const,
  PARTIALLY_RELEASED: 'PARTIALLY_RELEASED' as const,
  FULLY_RELEASED: 'FULLY_RELEASED' as const,
  EXPIRED: 'EXPIRED' as const,
  DISPOSED: 'DISPOSED' as const,
} as const;

export type QualityGrade = 'A' | 'B' | 'C' | 'REJECTED';
export const QualityGrade = {
  A: 'A' as const,
  B: 'B' as const,
  C: 'C' as const,
  REJECTED: 'REJECTED' as const,
} as const;

export type TransactionType = 'INTAKE' | 'PARTIAL_RELEASE' | 'FULL_RELEASE' | 'QUALITY_UPDATE' | 'WEIGHT_ADJUSTMENT' | 'TRANSFER';
export const TransactionType = {
  INTAKE: 'INTAKE' as const,
  PARTIAL_RELEASE: 'PARTIAL_RELEASE' as const,
  FULL_RELEASE: 'FULL_RELEASE' as const,
  QUALITY_UPDATE: 'QUALITY_UPDATE' as const,
  WEIGHT_ADJUSTMENT: 'WEIGHT_ADJUSTMENT' as const,
  TRANSFER: 'TRANSFER' as const,
} as const;

export type InvoiceStatus = 'DRAFT' | 'ISSUED' | 'PARTIALLY_PAID' | 'PAID' | 'OVERDUE' | 'CANCELLED';
export const InvoiceStatus = {
  DRAFT: 'DRAFT' as const,
  ISSUED: 'ISSUED' as const,
  PARTIALLY_PAID: 'PARTIALLY_PAID' as const,
  PAID: 'PAID' as const,
  OVERDUE: 'OVERDUE' as const,
  CANCELLED: 'CANCELLED' as const,
} as const;

export type ListingStatus = 'ACTIVE' | 'SOLD' | 'EXPIRED' | 'WITHDRAWN';
export const ListingStatus = {
  ACTIVE: 'ACTIVE' as const,
  SOLD: 'SOLD' as const,
  EXPIRED: 'EXPIRED' as const,
  WITHDRAWN: 'WITHDRAWN' as const,
} as const;

export type OrderStatus = 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'DISPATCHED' | 'COMPLETED' | 'CANCELLED';
export const OrderStatus = {
  PENDING_APPROVAL: 'PENDING_APPROVAL' as const,
  APPROVED: 'APPROVED' as const,
  REJECTED: 'REJECTED' as const,
  DISPATCHED: 'DISPATCHED' as const,
  COMPLETED: 'COMPLETED' as const,
  CANCELLED: 'CANCELLED' as const,
} as const;

export type UserDocType = 'AADHAAR_FRONT' | 'AADHAAR_BACK' | 'PAN_CARD' | 'GST_CERTIFICATE' | 'BUSINESS_LICENSE' | 'PHOTO_ID' | 'OTHER';
export const UserDocType = {
  AADHAAR_FRONT: 'AADHAAR_FRONT' as const,
  AADHAAR_BACK: 'AADHAAR_BACK' as const,
  PAN_CARD: 'PAN_CARD' as const,
  GST_CERTIFICATE: 'GST_CERTIFICATE' as const,
  BUSINESS_LICENSE: 'BUSINESS_LICENSE' as const,
  PHOTO_ID: 'PHOTO_ID' as const,
  OTHER: 'OTHER' as const,
} as const;

export type NotificationType = 'TEMPERATURE_ALERT' | 'LOT_EXPIRY_WARNING' | 'INVOICE_OVERDUE' | 'CHAMBER_CAPACITY_WARNING' | 'SYSTEM';
export const NotificationType = {
  TEMPERATURE_ALERT: 'TEMPERATURE_ALERT' as const,
  LOT_EXPIRY_WARNING: 'LOT_EXPIRY_WARNING' as const,
  INVOICE_OVERDUE: 'INVOICE_OVERDUE' as const,
  CHAMBER_CAPACITY_WARNING: 'CHAMBER_CAPACITY_WARNING' as const,
  SYSTEM: 'SYSTEM' as const,
} as const;

// ════════════════════════════════════════════════
// Models (scalar fields only — no relations)
// ════════════════════════════════════════════════

export interface User {
  id: string;
  fullName: string;
  email: string | null;
  phone: string;
  phoneVerified: boolean;
  role: UserRole;
  status: UserStatus;
  registrationNumber: string | null;
  facilityId: string | null;
  avatarUrl: string | null;
  preferredLang: string;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  state: string | null;
  pincode: string | null;
  aadhaarVerified: boolean;
  kycVerified: boolean;
  kycVerifiedAt: string | null;
  kycSubmittedAt: string | null;
  kycRejectionReason: string | null;
  kycVerifiedById: string | null;
  landHolding: string | null;
  khasraNumber: string | null;
  villageName: string | null;
  district: string | null;
  gstNumber: string | null;
  businessName: string | null;
  businessType: string | null;
  lastLoginAt: string | null;
  pushToken: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string | null;
}

export interface UserSession {
  id: string;
  userId: string;
  deviceInfo: Record<string, unknown> | null;
  expiresAt: string;
  createdAt: string;
}

export interface UserDocument {
  id: string;
  userId: string;
  documentType: UserDocType;
  documentNumber: string | null;
  fileUrl: string;
  thumbnailUrl: string | null;
  fileSizeBytes: number | null;
  mimeType: string | null;
  status: DocumentStatus;
  rejectionReason: string | null;
  reviewedById: string | null;
  reviewedAt: string | null;
  uploadedAt: string;
  updatedAt: string;
}

export interface Facility {
  id: string;
  name: string;
  registrationNumber: string | null;
  addressLine1: string;
  addressLine2: string | null;
  city: string;
  district: string;
  state: string;
  pincode: string;
  latitude: number | null;
  longitude: number | null;
  totalCapacityMt: number;
  storageType: StorageType;
  status: FacilityStatus;
  operatingSince: string | null;
  ownerId: string;
  contactPhone: string | null;
  contactEmail: string | null;
  imageUrl: string | null;
  verifiedAt: string | null;
  verifiedBy: string | null;
  verificationNotes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Chamber {
  id: string;
  facilityId: string;
  chamberNumber: string;
  name: string | null;
  capacityMt: number;
  occupiedMt: number;
  targetTempMin: number | null;
  targetTempMax: number | null;
  targetHumidityMin: number | null;
  targetHumidityMax: number | null;
  commodityCategory: CommodityCategory | null;
  status: ChamberStatus;
  storageType: StorageType;
  createdAt: string;
  updatedAt: string;
}

export interface FacilityDocument {
  id: string;
  facilityId: string;
  documentType: DocumentType;
  documentNumber: string | null;
  fileUrl: string;
  issuedDate: string | null;
  expiryDate: string | null;
  status: DocumentStatus;
  reviewedById: string | null;
  reviewedAt: string | null;
  reviewNotes: string | null;
  uploadedAt: string;
  uploadedById: string;
}

export interface FacilityPricing {
  id: string;
  facilityId: string;
  commodityCategory: CommodityCategory;
  pricingModel: PricingModel;
  rateAmount: number;
  rateCurrency: string;
  status: PricingStatus;
  adminApproved: boolean;
  maxAllowedRate: number | null;
  effectiveFrom: string;
  effectiveUntil: string | null;
  createdAt: string;
  updatedAt: string;
  createdById: string;
}

export interface InventoryLot {
  id: string;
  lotNumber: string;
  receiptNumber: string;
  qrCodeData: string | null;
  facilityId: string;
  chamberId: string;
  depositorId: string;
  commodityCategory: CommodityCategory;
  commodityName: string;
  intakeWeightKg: number;
  currentWeightKg: number;
  bagCount: number | null;
  qualityGrade: QualityGrade | null;
  qualityNotes: string | null;
  moistureContent: number | null;
  intakeDate: string;
  expectedRelease: string | null;
  actualReleaseDate: string | null;
  status: LotStatus;
  appliedRate: number | null;
  pricingModel: PricingModel | null;
  totalRentAccrued: number;
  totalRentPaid: number;
  createdAt: string;
  updatedAt: string;
  createdById: string;
}

export interface InventoryTransaction {
  id: string;
  lotId: string;
  transactionType: TransactionType;
  weightKg: number;
  bagCount: number | null;
  notes: string | null;
  gatePassNumber: string | null;
  authorizedById: string | null;
  depositorApproved: boolean;
  performedAt: string;
  performedById: string;
}

export interface Invoice {
  id: string;
  invoiceNumber: string;
  facilityId: string;
  depositorId: string;
  lotId: string | null;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  paidAmount: number;
  billingPeriodStart: string | null;
  billingPeriodEnd: string | null;
  issueDate: string;
  dueDate: string;
  status: InvoiceStatus;
  createdAt: string;
  updatedAt: string;
  createdById: string;
}

export interface InvoiceLineItem {
  id: string;
  invoiceId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  createdAt: string;
}

export interface AuditLog {
  id: string;
  userId: string | null;
  userRole: UserRole | null;
  action: string;
  entityType: string;
  entityId: string;
  oldValues: Record<string, unknown> | null;
  newValues: Record<string, unknown> | null;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

export interface TemperatureReading {
  id: string;
  chamberId: string;
  temperature: number;
  humidity: number | null;
  sensorId: string | null;
  isAlert: boolean;
  recordedAt: string;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  read: boolean;
  actionUrl: string | null;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

export interface Payment {
  id: string;
  invoiceId: string;
  amount: number;
  paymentMethod: PaymentMethod;
  referenceNumber: string | null;
  notes: string | null;
  paidAt: string;
  recordedById: string;
  createdAt: string;
}

export interface MarketListing {
  id: string;
  lotId: string;
  sellerId: string;
  askingPricePerKg: number;
  minQuantityKg: number | null;
  description: string | null;
  status: ListingStatus;
  listedAt: string;
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Order {
  id: string;
  listingId: string;
  buyerId: string;
  quantityKg: number;
  agreedPricePerKg: number;
  totalAmount: number;
  status: OrderStatus;
  otpCode: string | null;
  otpExpiresAt: string | null;
  approvedAt: string | null;
  rejectedReason: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface FacilityReview {
  id: string;
  facilityId: string;
  userId: string;
  rating: number;
  comment: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface WarehouseReceipt {
  id: string;
  lotId: string;
  receiptNumber: string;
  wdraRepoId: string | null;
  isNegotiable: boolean;
  isPledged: boolean;
  pledgedTo: string | null;
  pledgeAmount: number | null;
  pledgeDate: string | null;
  issuedAt: string;
  expiresAt: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface EscrowTransaction {
  id: string;
  orderId: string;
  amount: number;
  buyerPaidAt: string | null;
  sellerReleasedAt: string | null;
  loanDeduction: number;
  netToSeller: number | null;
  pgReferenceId: string | null;
  pgProvider: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface IoTDevice {
  id: string;
  facilityId: string;
  chamberId: string | null;
  deviceId: string;
  deviceType: string;
  mqttTopic: string;
  isActive: boolean;
  lastHeartbeat: string | null;
  firmwareVersion: string | null;
  description: string | null;
  createdAt: string;
  updatedAt: string;
}

// ════════════════════════════════════════════════
// API Response Types
// ════════════════════════════════════════════════

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data: T | null;
  meta?: PaginationMeta;
  error?: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}

export interface ApiListResponse<T> {
  success: boolean;
  data: T[];
  meta: PaginationMeta;
}
