/**
 * ColdStorage — Shared Types Generator
 *
 * Extracts enum and model types from the Prisma schema and generates
 * a framework-agnostic TypeScript file that can be consumed by:
 *   - frontend (Next.js web dashboard)
 *   - mobile (React Native/Expo app)
 *   - any future client
 *
 * Run: node shared/generate-types.mjs
 *      (or: npm run types:generate from the workspace root)
 *
 * The generated file has ZERO runtime dependencies — it contains only
 * TypeScript type definitions and string-enum objects.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = join(__dirname, '..', 'backend', 'prisma', 'schema.prisma');
const OUTPUT_PATH = join(__dirname, 'types', 'index.ts');

const schema = readFileSync(SCHEMA_PATH, 'utf-8');

// ──────────────────────────────────────────────
// 1. Extract enums
// ──────────────────────────────────────────────
const enumRegex = /enum\s+(\w+)\s*\{([^}]+)\}/g;
const enums = [];
let match;

while ((match = enumRegex.exec(schema)) !== null) {
  const name = match[1];
  const values = match[2]
    .split('\n')
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('//') && !line.startsWith('@@'));
  enums.push({ name, values });
}

// ──────────────────────────────────────────────
// 2. Extract models (fields only, no relations)
// ──────────────────────────────────────────────
const modelRegex = /model\s+(\w+)\s*\{([\s\S]*?)^\}/gm;
const models = [];

while ((match = modelRegex.exec(schema)) !== null) {
  const name = match[1];
  const body = match[2];
  const fields = [];

  for (const line of body.split('\n')) {
    const trimmed = line.trim();
    // Skip empty lines, comments, @@-level attributes
    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('@@')) continue;

    // Parse: fieldName  Type  @attributes...
    const fieldMatch = trimmed.match(/^(\w+)\s+(\S+?)(\?)?(\s+.*)?$/);
    if (!fieldMatch) continue;

    const [, fieldName, rawType, optional, attrs] = fieldMatch;

    // Skip sensitive fields that should never be in client types
    const SENSITIVE_FIELDS = new Set([
      'passwordHash', 'refreshToken', 'aadhaarNumber', 'panNumber',
    ]);
    if (SENSITIVE_FIELDS.has(fieldName)) continue;

    // Skip relation fields (Type starts with uppercase and isn't a Prisma scalar or enum)
    const isRelation = rawType.endsWith('[]') && /^[A-Z]/.test(rawType);
    const isRelationSingular = /^[A-Z]/.test(rawType) && !isPrismaType(rawType) && !isEnumType(rawType);

    if (isRelation || isRelationSingular) continue;

    const tsType = prismaToTs(rawType, optional === '?');
    fields.push({
      name: fieldName,
      type: tsType.type,
      optional: tsType.optional,
    });
  }

  if (fields.length > 0) {
    models.push({ name, fields });
  }
}

function isPrismaType(t) {
  return ['String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'Decimal', 'BigInt', 'Bytes'].includes(t);
}

function isEnumType(t) {
  return enums.some(e => e.name === t);
}

function prismaToTs(prismaType, isOptional) {
  const nullable = isOptional;
  let tsType;

  switch (prismaType) {
    case 'String':   tsType = 'string'; break;
    case 'Int':
    case 'Float':
    case 'Decimal':  tsType = 'number'; break;
    case 'BigInt':   tsType = 'bigint'; break;
    case 'Boolean':  tsType = 'boolean'; break;
    case 'DateTime': tsType = 'string'; break;  // JSON serialized as ISO string
    case 'Json':     tsType = 'Record<string, unknown>'; break;
    case 'Bytes':    tsType = 'Buffer'; break;
    default:
      // Check if it's an enum
      if (isEnumType(prismaType)) {
        tsType = prismaType;
      } else {
        tsType = 'unknown';
      }
  }

  return {
    type: nullable ? `${tsType} | null` : tsType,
    optional: false,
  };
}

// ──────────────────────────────────────────────
// 3. Generate output
// ──────────────────────────────────────────────
let output = `/**
 * ColdStorage — Shared Types (Auto-Generated)
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: node shared/generate-types.mjs
 *
 * Source: backend/prisma/schema.prisma
 * Generated: ${new Date().toISOString()}
 */

// ════════════════════════════════════════════════
// Enums
// ════════════════════════════════════════════════

`;

for (const e of enums) {
  // Generate both a type union and a const object (for runtime usage)
  output += `export type ${e.name} = ${e.values.map(v => `'${v}'`).join(' | ')};\n`;
  output += `export const ${e.name} = {\n`;
  for (const v of e.values) {
    output += `  ${v}: '${v}' as const,\n`;
  }
  output += `} as const;\n\n`;
}

output += `// ════════════════════════════════════════════════
// Models (scalar fields only — no relations)
// ════════════════════════════════════════════════

`;

for (const m of models) {
  output += `export interface ${m.name} {\n`;
  for (const f of m.fields) {
    output += `  ${f.name}: ${f.type};\n`;
  }
  output += `}\n\n`;
}

// ──────────────────────────────────────────────
// 4. Add API response types (framework-agnostic)
// ──────────────────────────────────────────────
output += `// ════════════════════════════════════════════════
// API Response Types
// ════════════════════════════════════════════════

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  data: T | null;
  meta?: PaginationMeta;
  error?: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}

export interface ApiListResponse<T> {
  success: boolean;
  data: T[];
  meta: PaginationMeta;
}
`;

// ──────────────────────────────────────────────
// 5. Write output
// ──────────────────────────────────────────────
mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, output, 'utf-8');

console.log(`✅ Generated shared types:`);
console.log(`   ${enums.length} enums`);
console.log(`   ${models.length} models`);
console.log(`   → ${OUTPUT_PATH}`);
